services:
  backend:
    image: node:16.13.2
    command: sh -c "npm i && npm run start:dev"

    working_dir: /app
    volumes:
      - "./:/app"
    restart: always
    depends_on:
      - db
    networks:
      - internal

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: app
    ports:
      - 3307:3306
    volumes:
      - "./dbVolume/dev:/var/lib/mysql"
    restart: always
    networks:
      - internal

networks:
  internal:
