volumes:
  node_modules:

services:
  backend:
    image: node:16.13.2
    command: sh -c "npm i && npm run start:${NODE_ENV}"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
      - node_modules:/app/node_modules

    restart: always
    depends_on:
      - db
    networks:
      - internal

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: app
      TZ: Asia/Seoul
    ports:
      - 3307:3306
    volumes:
      - ./dbVolume/${NODE_ENV}:/var/lib/mysql
    restart: always
    networks:
      - internal

networks:
  internal:


